# Generated by Django 4.0.5 on 2022-08-27 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=50)),
                ('institute_subject', models.CharField(max_length=10)),
                ('institute_startDate', models.DateField()),
                ('institute_endDate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceboo_link', models.CharField(max_length=50)),
                ('attached_org_number', models.IntegerField(default=0)),
                ('reffered_person_email', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('working_area', models.CharField(max_length=50)),
                ('photo', models.ImageField(default='default_img1.png', upload_to='image')),
                ('phone', models.IntegerField()),
                ('father_name', models.CharField(max_length=30)),
                ('father_phone', models.ImageField(upload_to='')),
                ('mother_name', models.CharField(max_length=30)),
                ('mother_phone', models.ImageField(upload_to='')),
                ('gender', models.CharField(max_length=6)),
                ('religin', models.CharField(max_length=10)),
                ('technology_skill', models.CharField(max_length=40)),
                ('cultural_skill', models.CharField(max_length=40)),
                ('hobby', models.CharField(max_length=30)),
                ('proffession', models.CharField(max_length=40)),
                ('proffession_position', models.CharField(max_length=40)),
                ('DOB', models.DateField()),
                ('Natiolality', models.CharField(max_length=30)),
                ('Identity_photo', models.ImageField(default='default_img2.png', upload_to='identity')),
                ('present_address', models.CharField(max_length=100)),
                ('permenent_address', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('intest_blood_donating', models.CharField(max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_way', models.CharField(max_length=20)),
                ('trxid', models.CharField(max_length=40)),
                ('ammount', models.IntegerField(default=0)),
                ('varified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
