# Generated by Django 4.0.5 on 2022-09-07 03:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Donate',
        ),
    ]
